export const useBanks = () => {
	const banks = [
		{ label: "BANAMEX" },
		{ label: "BANCOMEXT" },
		{ label: "BANOBRAS" },
		{ label: "BBVA" },
		{ label: "SANTANDER" },
		{ label: "BANJERCITO" },
		{ label: "HSBC" },
		{ label: "BAJIO" },
		{ label: "IXE" },
		{ label: "INBURSA" },
		{ label: "INTERACCIONES" },
		{ label: "MIFEL" },
		{ label: "SCOTIABANK" },
		{ label: "BANREGIO" },
		{ label: "INVEX" },
		{ label: "BANSI" },
		{ label: "AFIRME" },
		{ label: "BANORTE" },
		{ label: "THE ROYAL BANK" },
		{ label: "AMERICAN EXPRESS" },
		{ label: "BAMSA" },
		{ label: "TOKYO" },
		{ label: "JP MORGAN" },
		{ label: "BMONEX" },
		{ label: "VE POR MAS" },
		{ label: "ING" },
		{ label: "DEUTSCHE" },
		{ label: "CREDIT SUISSE" },
		{ label: "BANCO AZTECA" },
		{ label: "AUTOFIN" },
		{ label: "BARCLAYS" },
		{ label: "COMPARTAMOS" },
		{ label: "BANCO FAMSA" },
		{ label: "BMULTIVA" },
		{ label: "ACTINVER" },
		{ label: "WAL-MART" },
		{ label: "NAFIN" },
		{ label: "INTERBANCO" },
		{ label: "BANCOPPEL" },
		{ label: "ABC CAPITAL" },
		{ label: "UBS BANK" },
		{ label: "CONSUBANCO" },
		{ label: "VOLKSWAGEN" },
		{ label: "CIBANCO" },
		{ label: "BBASE" },
		{ label: "BANSEFI" },
		{ label: "HIPOTECARIA FEDERAL" },
		{ label: "MONEXCB" },
		{ label: "GBM" },
		{ label: "MASARI" },
		{ label: "VALUE" },
		{ label: "ESTRUCTURADORES" },
		{ label: "TIBER" },
		{ label: "VECTOR" },
		{ label: "B&amp;B" },
		{ label: "ACCIVAL" },
		{ label: "MERRILL LYNCH" },
		{ label: "FINAMEX" },
		{ label: "VALMEX" },
		{ label: "UNICA" },
		{ label: "MAPFRE" },
		{ label: "PROFUTURO" },
		{ label: "CB ACTINVER" },
		{ label: "OACTIN" },
		{ label: "SKANDIA" },
		{ label: "CBDEUTSCHE" },
		{ label: "ZURICH" },
		{ label: "ZURICHVI" },
		{ label: "SU CASITA" },
		{ label: "CB INTERCAM" },
		{ label: "CI BOLSA" },
		{ label: "BULLTICK CB" },
		{ label: "STERLING" },
		{ label: "FINCOMUN" },
		{ label: "HDI SEGUROS" },
		{ label: "ORDER" },
		{ label: "AKALA" },
		{ label: "CB JPMORGAN" },
		{ label: "REFORMA" },
		{ label: "STP" },
		{ label: "TELECOMM" },
		{ label: "EVERCORE" },
		{ label: "SKANDIA" },
		{ label: "SEGMTY" },
		{ label: "ASEA" },
		{ label: "KUSPIT" },
		{ label: "SOFIEXPRESS" },
		{ label: "UNAGRA" },
		{ label: "OPCIONES EMPRESARIALES DEL NOROESTE" },
		{ label: "CLS" },
		{ label: "INDEVAL" },
		{ label: "LIBERTAD" },
		{ label: "CHASE BANK" },
		{ label: "LIVERPOOL" },
		{ label: "N/A" },
		{ label: "Wells Fargo" },
		{ label: "Bank of America" },
		{ label: "Soriana" },
		{ label: "Bank tranks" },
		{ label: "C&amp;A" },
		{ label: "CITIBANK" },
		{ label: "BANAMEX/DEPOSITO" },
	].map((suggestion) => ({
		value: suggestion.label,
		label: suggestion.label,
	}));

	return [banks];
};
